---
- hosts: localhost
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
  roles :
    
    - {role: "nginx"}
    - {role: "postgresql"}
    - {role: "minio"}
    - {role: "piprecious"}
